[package]
name = "ikv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
jni = "0.21.1"
memmap2 = "0.9.0"
yaml-rust = "0.4.5"

[lib]
crate_type = ["cdylib"]